### ISSUE TITLE
API endpoints for mining on new registered node and consensus algorithm are not working

### ISSUE THREAD

**Issue by dhotrey** [theredditbandit/Blockchain#10]
The registering of a new node works fine but when i try to mine on the new generated node , it does not return any response and also when i try to use `/node/resolve` method the server returns an internal server error.

**Comment by dhotrey** [comment]
[/node/resolve](https://github.com/theredditbandit/Blockchain/blob/master/server.py#L97) and [Consensus algorithm](https://github.com/theredditbandit/Blockchain/blob/master/blockchain.py#L112)

**Comment by drCh405** [comment]
Can I work on this issue?
